### ISSUE TITLE
New version of docker breaks string comparision in init.sls

### ISSUE THREAD

**Issue by ejether** [saltstack-formulas/docker-formula#66]
The lastest version of Docker is 1.10.0.
Python:
>>> '1.10.0' < '1.7.1'
True
>>> '1.9.0' < '1.7.1'
False

https://github.com/saltstack-formulas/docker-formula/blob/master/docker/init.sls#L57

required the version to be greater than '1.7.1'

**Comment by myii** [comment]
@ejether Had the same problem as you.

Then realised that I could simply **remove (or comment out) the version number in the pillar** and then it runs `pkg.latest` via. the `else` instead.

**Comment by ejether** [comment]
Thats true, but when all of your production services are running in Docker and you run salt and it silently upgrades to the latest version and your Cassandra cluster and  your Elasticsearch cluster shut down, it becomes a bit of a problem. 

If I saw an easy way to fix it other than comment it out, I would have fixed and made a pull request.

**Comment by myii** [comment]
You're absolutely right and I assumed that you were after the latest release, hence the workaround suggestion.

There is a way to resolve this but it's not the nicest of solutions.  I've previously done something similar that was accepted into the `nfs-formula`, which you can see at: https://github.com/myii/nfs-formula/commit/fd7e247bc706f611e8e88bc37ddfb70139b61bc6#diff-5c53f7ed6159a6de6d566cddae09596a.

If you reckon that can be adapted for this situation then I might be able to put something together.

Even yesterday, I thought of doing that, only using the `major` and `minor` parts of the version number, since the `patch` number can get mixed in with other info, such as:

```
$ apt-cache policy docker-engine
docker-engine:
  Installed: 1.10.1-0~trusty
  Candidate: 1.10.1-0~trusty
  Version table:
 *** 1.10.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.10.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.9.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.9.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.8.3-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.8.2-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.8.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.8.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.7.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.7.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.6.2-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.6.1-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.6.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
     1.5.0-0~trusty 0
        500 https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
```

As long as `1.10` is seen as greater than `1.7`, that should be sufficient.

What do you think?

**Comment by myii** [comment]
@ejether So I've gone ahead and done it anyway since I needed this for some of my production systems as well.  Hope it helps you, too.

**Comment by gravyboat** [comment]
Closing since I've merged #68.

**Comment by ejether** [comment]
Thats for fixing that!

**Comment by myii** [comment]
@ejether You're welcome.  Thanks for the reminder, no more `pkg.latest` for me any more!
