### ISSUE TITLE
docker-config does not respect systemd

### ISSUE THREAD

**Issue by tedski** [saltstack-formulas/docker-formula#74]
`docker.docker-config` only edits `/etc/default/docker` which is unused on systemd nodes.  Upon detection of systemd, the states should use a systemd drop-in to override the package-supplied unit file.

**Comment by blbradley** [comment]
So, how about a systemd formula?

**Comment by morsik** [comment]
This formula should configure Docker inside `/etc/docker/daemon.json` which is preferred way to customize Docker instead of `/etc/default/docker`. Well… on RHEL-based it's `/etc/sysconfig/docker` and only when using RHEL packages. Docker from Docker repo does not use `/etc/sysconfig/docker` at all and you *need* to use `/etc/docker/daemon.json`.

**Comment by blbradley** [comment]
@morsik `docker.json` was introduced in Docker 1.10. Good find! Could reduce configuration complexity.

**Comment by noelmcloughlin** [comment]
Fixed in merged #256
